"""Fix audit_events.seq: add GENERATED BY DEFAULT AS IDENTITY.

Migration 0003 declared ``audit_events.seq`` as ``BIGINT NOT NULL`` with
``autoincrement=True``. SQLAlchemy silently drops ``autoincrement`` for
non-primary-key columns on the PostgreSQL dialect, so no sequence or
default was ever emitted — the first insert through ``audit.append``
fails with a ``NotNullViolation`` on ``seq``. This went undetected
because pure-logic tests never exercised the INSERT path.

Fix forward: attach a native Postgres identity generator to the column.
The existing advisory lock in ``app.services.audit.append`` keeps writers
serialised, so the identity-generated values remain monotonic alongside
the SHA-256 chain.

Preserves any rows already present (dev environments may have seeded
audit events by hand) by rewinding the identity sequence to
``MAX(seq) + 1`` before returning.
"""

from collections.abc import Sequence as Seq
from typing import Union

from alembic import op

revision: str = "0006"
down_revision: Union[str, None] = "0005"
branch_labels: Union[str, Seq[str], None] = None
depends_on: Union[str, Seq[str], None] = None


def upgrade() -> None:
    # Attach an identity generator. BY DEFAULT lets callers still supply an
    # explicit value (useful for data migrations / fixture loads) while
    # defaulting to the sequence when omitted, which is what the ORM does.
    op.execute(
        "ALTER TABLE audit_events "
        "ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY"
    )
    # If rows already exist (dev seed, prior manual inserts) the identity
    # starts at 1 and would collide with them. Advance it to MAX+1 so the
    # next ORM insert picks up cleanly. ``false`` here means "next call
    # returns this value", i.e. do not pre-consume.
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('audit_events', 'seq'),
            GREATEST(COALESCE((SELECT MAX(seq) FROM audit_events), 0) + 1, 1),
            false
        )
        """
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE audit_events ALTER COLUMN seq DROP IDENTITY IF EXISTS"
    )
